Refactor

diff --git a/bin/csv2meta b/bin/csv2meta
--- a/bin/csv2meta
+++ b/bin/csv2meta
@@ -54,91 +54,98 @@ META_KEYWORDS_FIELD="mwg:Keywords"
 # Functions
 # --------------------------------------
 
+function updateImage {
 
-function processCsv {
+	inputFile="${1}"
+	id="${2}"
+	title="${3}"
+	description="${4}"
+	keywords="${5}"
+
+	[ ! -f "${inputFile}" ] && { echo "File not found: ${inputFile}"; return 1; }
+
+	echo;
+	e_info "${inputFile}"
+	echo "New meta data"
+	echo "ID             : ${id}"
+	echo "title          : ${title}"
+	echo "description    : ${description}"
+	echo "keywords       : ${keywords}"
+
+
+	# Determine current values
+	IMAGE_ID=$(exiftool -s3 -"${META_ID_FIELD}" "${inputFile}")
+	IMAGE_TITLE=$(exiftool -s3 -"${META_TITLE_FIELD}" "${inputFile}")
+	IMAGE_DESCRIPTION=$(exiftool -s3 -"${META_DESCRIPTION_FIELD}" "${inputFile}")
+	IMAGE_KEYWORDS=$(exiftool -s3 -"${META_KEYWORDS_FIELD}" "${inputFile}")
+
+
+	# Split found keywords into array
+	declare -a keywords_array=()
+	OIFS=$IFS
+	IFS=', '
+	for keyword in $IMAGE_KEYWORDS; do keywords_array+=("${keyword}"); done
+	IFS=','
+	for keyword in $keywords; do keywords_array+=("${keyword}"); done
+	IFS=$OIFS
+
+
+	# Set to defaults if we got a blank result
+	NEW_ID="${title:-${IMAGE_ID}}"
+	NEW_TITLE="${title:-${IMAGE_TITLE}}"
+	NEW_DESCRIPTION="${description:-${IMAGE_DESCRIPTION}}"
+	NEW_KEYWORDS=($(echo "${keywords_array[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
+
+
+	# Build output filename
+	OUTPUT_FILE="${NEW_ID}.${inputFile#*.}"
+	OUTPUT_FILE="${inputFile}"
+
+
+
+	# Build exiftool CLI parameters
+	declare -a exiftool_params=(
+		-overwrite_original
+		-"${META_ID_FIELD}"="${NEW_ID}"
+		-"${META_TITLE_FIELD}"="${NEW_TITLE}"
+		-"${META_DESCRIPTION_FIELD}"="${NEW_DESCRIPTION}"
+		-"${META_KEYWORDS_FIELD}"="${NEW_KEYWORDS[@]}"
+		# -filename="${OUTPUT_FILE}"
+	)
+
+
+	# Update via exiftool
+	echo;
+	echo "Running exiftool:"
+	exiftool "${exiftool_params[@]}" "${inputFile}"
+
+
+	# Display results
+	echo;
+	echo "Meta data now is:"
+	exiftool -f \
+		-"${META_ID_FIELD}" \
+		-"${META_TITLE_FIELD}" \
+		-"${META_DESCRIPTION_FIELD}" \
+		-"${META_KEYWORDS_FIELD}" \
+		"${OUTPUT_FILE}"
+
+}
+
+
+function main {
+
 	CSV_FILE="${1}"
 
 	[ ! -f $CSV_FILE ] && { echo "${CSV_FILE} file not found"; exit 1; }
 
 	OLDIFS=$IFS
 	IFS=$'\t'
-	while read rawFile id title description keywords; do
-
-		echo;
-		e_info "${rawFile}"
-
-		# Skip if file not found
-		[ ! -f "${rawFile}" ] && { echo "File not found, skip."; continue; }
-
-
-		echo "New meta data"
-		echo "ID             : ${id}"
-		echo "title          : ${title}"
-		echo "description    : ${description}"
-		echo "keywords       : ${keywords}"
-
-
-		# Determine current values
-		IMAGE_ID=$(exiftool -s3 -"${META_ID_FIELD}" "${rawFile}")
-		IMAGE_TITLE=$(exiftool -s3 -"${META_TITLE_FIELD}" "${rawFile}")
-		IMAGE_DESCRIPTION=$(exiftool -s3 -"${META_DESCRIPTION_FIELD}" "${rawFile}")
-		IMAGE_KEYWORDS=$(exiftool -s3 -"${META_KEYWORDS_FIELD}" "${rawFile}")
-
-
-		# Split found keywords into array
-		declare -a keywords_array=()
-		OIFS=$IFS
-		IFS=', '
-		for keyword in $IMAGE_KEYWORDS; do keywords_array+=("${keyword}"); done
-		IFS=','
-		for keyword in $keywords; do keywords_array+=("${keyword}"); done
-		IFS=$OIFS
-
-
-		# Set to defaults if we got a blank result
-		NEW_ID="${title:-${IMAGE_ID}}"
-		NEW_TITLE="${title:-${IMAGE_TITLE}}"
-		NEW_DESCRIPTION="${description:-${IMAGE_DESCRIPTION}}"
-		NEW_KEYWORDS=($(echo "${keywords_array[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
-
-
-		# Build output filename
-		ext="${rawFile#*.}"
-		NEW_FILENAME="${title}.${ext}"
-		NEW_FILENAME="${rawFile}"
-
-
-		# Build exiftool CLI parameters
-		declare -a exiftool_params=(
-			-overwrite_original
-			-"${META_ID_FIELD}"="${NEW_ID}"
-			-"${META_TITLE_FIELD}"="${NEW_TITLE}"
-			-"${META_DESCRIPTION_FIELD}"="${NEW_DESCRIPTION}"
-			-"${META_KEYWORDS_FIELD}"="${NEW_KEYWORDS[@]}"
-			# -filename="${NEW_FILENAME}"
-		)
-
-
-		# Update via exiftool
-		echo;
-		echo "Running exiftool:"
-		exiftool "${exiftool_params[@]}" "${rawFile}"
-
-
-		# Display results
-		echo;
-		echo "Meta data now is:"
-		exiftool -f \
-		    -"${META_ID_FIELD}" \
-		    -"${META_TITLE_FIELD}" \
-		    -"${META_DESCRIPTION_FIELD}" \
-		    -"${META_KEYWORDS_FIELD}" \
-		    "${NEW_FILENAME}"
-
+	while read inputFile id title description keywords;
+	do
+		updateImage "${inputFile}" "${id}" "${title}" "${description}" "${keywords}" || continue
 	done < <(tail -n +2 ${CSV_FILE})
 	IFS=$OLDIFS
-
-	echo;
 }
 
 
@@ -147,7 +154,7 @@ function processCsv {
 # --------------------------------------
 
 
-for item in "${@}"
+for csvFile in "${@}"
 do
-	processCsv "${item}"
+	main "${csvFile}"
 done;
